---
title: Vehicle speed on different grounds
author: 'Maria Rosaria Nucera and Emanuel Soda'
date: '2022-08-03'
slug: vehicle-speed-on-different-grounds
categories: []
tags: []
---
# Import libraries
```{r,warning=FALSE,message=FALSE}
library("tidyverse")
```

# Import data
```{r}
frac<-readxl::read_excel("/Users/MariaRosariaNucera/Desktop/blog_data_science_bioinfo/Data/speed.xlsx")
```

# Pivot dataframe
```{r}
frac<-frac %>%
    pivot_longer(cols = c('Bike', 'Skateboard','Rollers'), 
                 names_to = "vehicle", 
                 values_to = "speed")%>%
    mutate(vehicle=fct_reorder(vehicle,speed))
```
# Remove null values
```{r}
frac<-na.omit(frac)
```

# Plot
```{r}
ggplot(frac, aes(x = vehicle, y = speed))+
    geom_point(aes( colour=ground),
      position=position_jitterdodge( jitter.width = 0.1,
      dodge.width = 0.5), alpha=0.5)+ 
    ggdist::stat_halfeye( 
      aes(fill = stat(y) ) ,
      adjust = .5, width = .6,show.legend = FALSE,
      .width = 0, justification = -.5,
      point_colour = NA)+ 
      coord_flip() + ylim(0, 50)+
      labs(color="Ground",x=" ", y= "Speed")+
      scale_fill_gradient(low = 'white',high='black')+
      scale_colour_manual(values=c("royalblue","#FAB95B",'#827397',
     "darkgreen","#AF6B58") ,limits=c("wet"  ,"sandy", "rock", 
     "hill"     ,"flat"))+theme_light()+ 
      guides(colour =   guide_legend(override.aes = list(size=5)))
```

